server:
  port : 8140
spring:
  application:
    name : user-micro
  devtools:
    restart:
      enabled : true
app:
  datasource:
    url: "jdbc:postgresql://ec2-44-195-240-222.compute-1.amazonaws.com:5432/d58n869qbihu3l"
    username: "sskxvbppijiykg"
    password: 4813c95e36a16807f57c833e4e5dc5b886bb021ac413e71477fad7fc28255eca
    driver-class-name: org.postgresql.Driver
    configuration:
      maximum-pool-size: 30

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

gateway:
  ip: "192.168.1.2"

# 10 days:
token:
  expiration_time: 864000000
  secret: 4sfdg4sdfbgv5z4dgd

user:
  login:
    url: "/api/user/login"