server:
  port : 8200
spring:
  application:
    name : api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: offer-get
        uri: lb://OFFER-MICRO
        predicates:
        - Path=/api/offer/list
        - Method=GET
      - id: offer-create
        uri: lb://OFFER-MICRO
        predicates:
        - Path=/api/offer/create
        - Method=POST
      - id: offer-update
        uri: lb://OFFER-MICRO
        predicates:
        - Path=/api/offer/update
        - Method=PUT
      - id: offer-delete
        uri: lb://OFFER-MICRO
        predicates:
        - Path=/api/offer/delete
        - Method=DELETE
      - id: advert-get
        uri: lb://ADVERT-MICRO
        predicates:
        - Path=/api/advert/list
        - Method=GET
      - id: advert-create
        uri: lb://ADVERT-MICRO
        predicates:
        - Path=/api/advert/create
        - Method=POST
      - id: advert-update
        uri: lb://ADVERT-MICRO
        predicates:
        - Path=/api/advert/update
        - Method=PUT
      - id: advert-delete
        uri: lb://ADVERT-MICRO
        predicates:
        - Path=/api/advert/delete
        - Method=DELETE
      - id: user-create
        uri: lb://USER-MICRO
        predicates:
        - Path=/api/user/create
        - Method=POST
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/