server:
  port : 8130
spring:
  application:
    name : advert-micro
  devtools:
    restart:
      enabled : true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
