SELECT OFFER_ID AS offerID,CUSTOMER_ID AS customerID,PROVIDER_ID AS serviceProviderID,
       ADVERT_ID AS advertID,CONDITIONS AS freeText,STATUS AS serviceStatus,SESSION AS session
FROM OFFER
WHERE PROVIDER_ID = ?1 AND SESSION = ?2