SELECT "OFFER_ID" AS OFFERID,
       "PROVIDER_ID" AS SERVICEPROVIDERID,
       "ADVERT_ID" AS ADVERTID,
       "FREE_TEXT" AS FREETEXT,
       "SERVICE_STATUS" AS SERVICESTATUS,
       "OFFER_TIME" AS OFFERTIME
FROM "OFFER"
WHERE "ADVERT_ID" = :advertId
  AND "SERVICE_STATUS" = :serviceStatus
  AND "PROVIDER_ID" = :providerId;